/*
TMDC11 - the template - TODO
_____________________________________________________________________________

[X]get the template
(x) download
(x) open it in MSVC express or sumfin

[ ]study the framework
( ) read the comments
( ) play around changing values and whatnots
( ) understand how it works

[ ]customize to your design
( ) remove useless stuff
( ) clean ugly stuff
( ) add new stuff

====-=------------------------=-----------------------------=--------========

[ ]storyboard
( ) plan storyboard
( ) build/code scenes

[ ]make data
( ) music
( ) graphics
( ) special effect
( ) credits
( ) title
( ) greetings

[ ]integrate data
( ) music
( ) graphics
( ) special effect
( ) credits
( ) title
( ) greetings

[ ]polishing
( ) synch
( ) transitions

[ ]packaging
( ) nfo
( ) txt
( ) zip
( ) reread rules to be sure
_____________________________________________________________________________

CREDZ:
 Most of the code and all assets from this template, made by BarZoule/ND^Bawlz
 JOES11.IT shamelessly ripped and customized from Jesus On Es
 Libcaca by Sam Hocevar
 Possibly additional misc code by Guybrush, Hardliner and Blacklight
 Most of the code was used (and made for)
  Signal.2.Noize (tmdc8),
  Signal to Droids (tmdc9),
  Session One (tmdc10),
  ClockWerk (tmdc10),
  as well as some unreleased GP2X prods.

GREETS:
 ACiD
 Bawlz
 Conspiracy
 Crimson Shine
 Foobug
 Fairlight
 GL.Fusion
 Hornet
 Hypercube
 Marsharls
 Mostly Harmless
 Northern Dragons
 Numedia Cyclops
 Orb
 Style
 tAAt
 The Gang
 Trailer Park Demos
 XPLSV
_____________________________________________________________________________

*/